name: rust-rustfmt-check
description: Format Rust code using rustfmt
author: mbrobbel
branding:
  icon: feather
  color: yellow

inputs:
  token:
    description: GitHub token
    required: true
  args:
    description: Arguments for cargo. Not for rustfmt options.
    required: false
  mode:
    description: Output mode (commit, review or pull)
    default: commit
    required: false
  commit-message:
    description: Commit message for formatting commits.
    required: false
    default: Format Rust code using rustfmt

runs:
  using: node20
  main: dist/index.js
